name: Build Yugioh TG3 APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Extrair projeto
        run: |
          unzip -o YugiohTG3-v2.zip
          ls -la YugiohTG3

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      - name: Compilar APK
        working-directory: YugiohTG3
        run: gradle assembleDebug --no-daemon

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Yugioh-TG3-APK
          path: YugiohTG3/app/build/outputs/apk/debug/app-debug.apk
